### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by yazinsai** [artemtam/checkout-frames-react#20]
Getting this error message when adding the package using `npm i checkout-frames-react` on a NextJS project:

```txt
ncaught SyntaxError: Cannot use import statement outside a module
    at <unknown> (./node_modules/checkout-frames-react/dist/index.js:1)
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1166:20)
    at Module._compile (node:internal/modules/cjs/loader:1210:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at checkout-frames-react (./.next/server/pages/fund/[symbol].js:578:18)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/PaymentModal/CardForm.js:9:79)
    at ./src/components/PaymentModal/CardForm.js (./.next/server/pages/fund/[symbol].js:383:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/PaymentModal/PaymentModal.js:14:67)
    at __webpack_require__.a (./.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/components/PaymentModal/PaymentModal.js:1:21)
    at ./src/components/PaymentModal/PaymentModal.js (./.next/server/pages/fund/[symbol].js:394:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/PaymentModal/index.js:6:71)
    at __webpack_require__.a (./.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/components/PaymentModal/index.js:1:21)
    at ./src/components/PaymentModal/index.js (./.next/server/pages/fund/[symbol].js:405:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/providers/OnboardingProvider.js:12:82)
    at __webpack_require__.a (./.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/providers/OnboardingProvider.js:1:21)
    at ./src/providers/OnboardingProvider.js (./.next/server/pages/fund/[symbol].js:493:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/FundPerformance/InvestButton.js:10:87)
    at __webpack_require__.a (./.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/components/FundPerformance/InvestButton.js:1:21)
    at ./src/components/FundPerformance/InvestButton.js (./.next/server/pages/fund/[symbol].js:339:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/fund/[symbol].jsx:14:98)
    at __webpack_require__.a (./.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/pages/fund/[symbol].jsx:1:21)
    at ./src/pages/fund/[symbol].jsx (./.next/server/pages/fund/[symbol].js:482:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (./.next/server/pages/fund/[symbol].js:1061:39)
    at <unknown> (./.next/server/pages/fund/[symbol].js:1062:28)
    at Object.<anonymous> (./.next/server/pages/fund/[symbol].js:1065:3)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.requirePage (./node_modules/next/dist/server/require.js:88:12)
    at <unknown> (./node_modules/next/dist/server/load-components.js:48:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by artemtam** [comment]
Please, use https://github.com/checkout/frames-react/. This package is deprecated.
